name: Publish Python Package with OIDC

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@latest
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        oidc_token: ${{ steps.oidc.outputs.token }}
